inputs:
  data: /home/mdicosta/hf_pid_studies/skimming/datasets/pbpb/skimmed/data/AO2D_LHC23zzh_small_k0s.parquet
  mc: /home/mdicosta/hf_pid_studies/skimming/datasets/pbpb/skimmed/mc/AO2D_LHC25a5_medium_k0s.parquet

mother_mass_var_name: fMassK0
mother_pt_var_name: fPt
variables_to_plot: [fNSigmaTpcPosPi, fNSigmaTpcNegPi, fNSigmaTofPosPi, fNSigmaTofNegPi]
dau_names: [pos_pi, neg_pi]
dau_pt_var_names: [fPtPos, fPtNeg] # relative to the variables_to_plot
mass_range: [0.43, 0.57]
fit_config:
  bkg_func: chebpol1
  mean: 0.5
  sigma: 0.01
  nl: 4
  nr: 5
  alphal: 3
  alphar: 3
  c0: 5000
  c1: -1000
max_workers: 2
pt_bins: [0., 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.6, 2.4] #, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.5, 2.0, 4.0]
cent_bins: [
            [0, 80],
           ]
occ_bins: [ 
            [0, 10000],
            [10000, 20000],
            [20000, 40000],
            [40000, 99999999]
          ]

output:
  dir: distributions/k0s/pbpb/occ_pt_diff_cent_int